openapi: 3.0.3
info:
  title: Swagger Animal - OpenAPI 3.0
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
- url: http://localhost:8080
paths:
  /animals:
    get:
      tags:
      - animal
      summary: Get all animals
      operationId: getAllAnimals
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AnimalResponse'
        "204":
          description: No content
    post:
      tags:
      - animal
      summary: Add a new animal
      operationId: addAnimal
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnimalRequest'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnimalResponse'
              example:
                id: 1
                name: Bella
                species: Dog
                age: 5
        "400":
          description: Invalid input
  /animals/{animalId}:
    get:
      tags:
      - animal
      summary: Get animal by ID
      operationId: getAnimalById
      parameters:
      - name: animalId
        in: path
        description: ID of animal to return
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnimalResponse'
              example:
                id: 1
                name: Bella
                species: Dog
                age: 5
        "404":
          description: Animal not found
    put:
      tags:
      - animal
      summary: Update an animal
      operationId: updateAnimal
      parameters:
      - name: animalId
        in: path
        description: ID of animal to update
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnimalRequest'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnimalResponse'
              example:
                id: 1
                name: Max
                species: Cat
                age: 3
        "404":
          description: Animal not found
    delete:
      tags:
      - animal
      summary: Delete an animal
      operationId: deleteAnimal
      parameters:
      - name: animalId
        in: path
        description: ID of animal to delete
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "204":
          description: Animal deleted
        "404":
          description: Animal not found
components:
  schemas:
    Animal:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        species:
          type: string
        age:
          type: integer
          format: int32
    AnimalRequest:
      type: object
      properties:
        name:
          type: string
        species:
          type: string
        age:
          type: integer
          format: int32
    AnimalResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        species:
          type: string
        age:
          type: integer
          format: int32
